config/routes.rb
Rails.application.routes.draw do

  resources :books

  devise_for :users
  
  root 'pages#home'

  get 'dashboard' => 'pages#dashboard'

  post '/buy/:slug' => 'transactions#create', as: :buy

  get '/pickup/:guid' => 'transactions#pickup', as: :pickup 

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    
      user ||= User.new # guest user (not logged in)
      can :read, :all
      can :manage, Book do |book|
        book.try(:user) == user
      end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/book.rb
class Book < ActiveRecord::Base
  extend FriendlyId
  friendly_id :name, use: :slugged

  belongs_to :user
  has_many :sales
  has_attached_file :image
  has_attached_file :resource

  validates_attachment_content_type :image,
  content_type: /^image\/(png|gif|jpeg)/,
  message: "Only images allowed"

  validates_attachment_content_type :resource,
  content_type: ['application/pdf','binary/octet-stream'],
  message: "Only PDF documents allowed"

  validates :image, attachment_presence: true
  validates :resource, attachment_presence: true

  validates_numericality_of :price,
  greater_than: 49, message: "must be at least 50 cents"
end

app/models/sale.rb
class Sale < ActiveRecord::Base
  before_create :populate_guid
  belongs_to :book

  include AASM

  aasm column: 'state' do
    state :pending, initial: true
    state :processing
    state :finished
    state :errored

    event :process, after: :charge_card do
      transitions from: :pending, to: :processing
    end

    event :finish do
      transitions from: :processing, to: :finished
    end

    event :fail do
      transitions from: :processing, to: :errored
    end
  end

  def charge_card
    begin
      save!
      charge = Stripe::Charge.create(
        amount: self.amount,
        currency: "usd",
        card: self.stripe_token,
        description: "Sell Books"
      )
      self.update(stripe_id: charge.id)
      self.finish!
    rescue Stripe::StripeError => e
      self.update_attributes(error: e.message)
      self.fail!
    end
  end


  private

  def populate_guid
    self.guid = SecureRandom.uuid()
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :books
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_path, notice: "You are not authorized to access this area"
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :edit, :create, :uypdate, :destroy]

  # GET /books
  # GET /books.json
  def index
    @books = Book.where(availability: true)
  end

  # GET /books/1
  # GET /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
    authorize! :manage, @book
  end

  # POST /books
  # POST /books.json
  def create
    # @book = Book.new(book_params)
    @book = current_user.books.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:name, :author, :description, :price, :availability, :image, :resource)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :authenticate_user!, only: [:dashboard]
  
  def home
    if current_user # If user is logged in
      redirect_to books_path
    end

    @books = Book.last(4)
  end

  def dashboard
    @books = current_user.books
    @purchased = Sale.where(buyer_email: current_user.email)
    @sales = Sale.where(seller_email: current_user.email)
  end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  def create
    book = Book.find_by!(slug: params[:slug])
    sale = book.sales.create(
      amount: book.price,
      buyer_email: current_user.email,
      seller_email: book.user.email,
      stripe_token: params[:stripeToken])
    sale.process!

    if sale.finished?
      redirect_to pickup_url(guid: sale.guid), notice: "Transaction Successful"
    else
      redirect_to book_path(book), notice: "Something went wrong"
    end
  end

  def pickup
    @sale = Sale.find_by!(guid: params[:guid])
    @book = @sale.book
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/transaction_helper.rb
module TransactionHelper
end

app/views/books/_book.html.slim
.col-md-3
  .thumbnail
    = link_to book_path(book) do
	  = image_tag book.image.url(:original), class: "img-responsive"

    .caption
      p
      	strong = link_to book.name, book_path(book)
      	br
      	| $ #{book.price.to_f / 100}

app/views/books/_form.html.slim
= simple_form_for(@book, html: {class: "form-signin"}) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name, required: true, label: false, placeholder: "Name", input_html: {class: "form-control"}
    = f.input :author, required: true, label: false, placeholder: "Author's name", input_html: {class: "form-control"}
    = f.input :description, required: true, label: false, placeholder: "Description", input_html: {class: "form-control", rows: 5}
    = f.input :price, required: true, label: false, placeholder: "Price", input_html: {class: "form-control"}
    = f.input :image
    = f.input :resource
    .checkbox.text-center
      p Availability
      = f.input :availability, required: false, label: false

  .form-actions
    = f.button :submit, class: "btn btn-primary btn-block"

app/views/books/edit.html.slim
h1 Editing book

== render 'form'

= link_to 'Show', @book
'  | 
= link_to 'Back', books_path

app/views/books/index.html.slim
.row
  = render @books

app/views/books/new.html.slim
h1 New book

== render 'form'

= link_to 'Back', books_path

app/views/books/show.html.slim
.container
  .row
    .col-md-6 = image_tag @book.image.url(:original), class: "img-responsive"
    .col-md-6
      / .col-md-6
      h3 #{@book.name} by #{@book.author}
      p.justify #{@book.description}
      h4.text-right $ #{@book.price.to_f / 100}
      
    - if current_user
      = form_tag buy_path(slug: @book.slug) do
        
        script src="https://checkout.stripe.com/checkout.js" class="stripe-button" data-key="#{Rails.configuration.stripe[:publishable_key]}" data-name="Sell Books" data-description="#{@book.name}" data-amount="#{@book.price}" data-email="#{current_user.email}"
    - else 
      p Please Login first

= link_to 'Edit', edit_book_path(@book)
|  | 
= link_to 'Back', books_path

app/views/layouts/_header.html.slim
nav.navbar.navbar-default role="navigation" 
  .container-fluid
    /! Brand and toggle get grouped for better mobile display
    .navbar-header
      button.navbar-toggle.collapsed data-target="#bs-example-navbar-collapse-1" data-toggle="collapse" type="button" 
        span.sr-only Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      = link_to "Sell Books", root_path, class: "navbar-brand"
    /! Collect the nav links, forms, and other content for toggling
    #bs-example-navbar-collapse-1.collapse.navbar-collapse
      ul.nav.navbar-nav.navbar-right
        li = link_to "Books", books_path
        - if current_user
          li = link_to "Settings", edit_user_registration_path
          li = link_to "Dashboard", dashboard_path
          li = link_to "Logout", destroy_user_session_path, method: :delete
        - else
          li = link_to "Login", new_user_session_path

app/views/layouts/application.html.slim
doctype html
html
  head
    meta content="text/html" charset="UTF-8" http-equiv="Content-Type" 
    title Sell Books
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  body
    = render 'layouts/header'
    / .container
    - flash.each do |type, message|
      .alert.alert-info.fade-in
        button.close data-dismiss="alert" x
        = message
        
    .container
      = yield

app/views/pages/_books.html.slim
table.table.table-condensed.table-striped.table-bordered
  thead
    tr
      th ID
      th Name
      th Available
      th 
  tbody
  - @books.each do |book|
    tr
      td = book.id
      td = link_to book.name, book_path(book)
      td = book.availability
      td = link_to "Edit", edit_book_path(book)

app/views/pages/_purchased.html.slim
table.table.table-condensed.table-striped.table-bordered
  thead
    tr
      th Name
      th Date
  tbody
  - @purchased.each do |sale|
    tr
      td = link_to sale.book.name, pickup_path(sale.guid)
      td #{time_ago_in_words(sale.created_at)} ago 

app/views/pages/_sales.html.slim
table.table.table-condensed.table-striped.table-bordered
  thead
    tr
      th Name
      th Date
      th Buyer
  tbody
  - @sales.each do |sale|
    tr
      td = link_to sale.book.name, pickup_path(sale.guid)
      td #{time_ago_in_words(sale.created_at)} ago
      td = sale.buyer_email

app/views/pages/dashboard.html.slim
.row
  h1.text-center Dashboard
  .text-center = link_to "New Book", new_book_path, class: "btn btn-primary btn-sm"
  .clearfix
  .col-md-4
    .dash-box
      h3.text-center Books
    = render "books"
  .col-md-4
    .dash-box
      h3.text-center Purchased
    = render "purchased"
  .col-md-4
    .dash-box
      h3.text-center Sales
    = render "sales"

app/views/pages/home.html.slim
.jumbotron
  h1 Welcome to our store
  p The largest online Digital Books Store
  = link_to "Books", books_path, class: "btn btn-primary btn-large"
  |  
  = link_to "Sign Up", new_user_registration_path, class: "btn btn-primary btn-large"

.row
  = render @books

app/views/transactions/create.html.slim
h1 Transaction#create
p Find me in app/views/transaction/create.html.slim

app/views/transactions/pickup.html.slim
.row.text-center
  h1 Congratulations on your order #{@sale.guid}

  p Here is your download link: 
  = link_to "Download", @book.resource.url